### ISSUE TITLE
EULA Not Accepted and No Prompt Given

### ISSUE THREAD

**Issue by pkbarbiedoll** [fontist/vista-fonts-installer#14]
### **Issue: EULA Not Accepted and No Prompt Given**

**Description:**
When attempting to install the Vista fonts using the provided installer script (`vista-fonts-installer.sh`), the script does not correctly prompt for EULA acceptance, leading to an error that prevents font installation. Specifically, the script fails to offer an opportunity to accept the EULA before reporting the error. I tried passing "yes" to the script using `echo` but the issue persists.

**Steps to Reproduce:**
1. Run the following command:
    ```bash
    sudo curl -Ls https://raw.githubusercontent.com/metanorma/vista-fonts-installer/master/vista-fonts-installer.sh | sudo bash
    ```
2. Observe that the script downloads the required files and extracts them successfully, but fails to present a clear prompt to accept the EULA.
3. The script exits with an error stating: `Error: Unable to install some fonts. EULA not accepted.`

**Expected Behavior:**
The script should either:
- Prompt the user to accept the EULA explicitly during the installation process.
- Provide a way to pass a flag (e.g., `--accept-eula`) to automatically accept the EULA.

**Actual Behavior:**
The script fails to provide an option to accept the EULA and proceeds to error out, causing the installation to fail.

**Attempts to Work Around:**
I tried passing "yes" using the following command but it did not resolve the issue:
```bash
echo "yes" | sudo curl -Ls https://raw.githubusercontent.com/metanorma/vista-fonts-installer/master/vista-fonts-installer.sh | bash
```

**Environment:**

- **OS:** Ubuntu 24.04
- **Script:** `vista-fonts-installer.sh`
- **Command:**
  ```bash
  curl -Ls https://raw.githubusercontent.com/metanorma/vista-fonts-installer/master/vista-fonts-installer.sh | sudo bash

**Logs/Output:**
```bash
Do you accept EULA? (yes/no): [macos-vista-fonts-installer] Error: Unable to install some fonts. EULA not accepted

**Request:**
Please add either:
1. A proper prompt to accept the EULA.
2. A flag to automatically accept the EULA in non-interactive installs.

Thank you for your attention to this matter!

**Comment by ronaldtse** [comment]
@pkbarbiedoll this script has been deprecated. We recommend using Fontist, with documentation available at https://www.fontist.org/fontist/.
