### ISSUE TITLE
Microsoft EULA

### ISSUE THREAD

**Issue by raffaem** [fontist/vista-fonts-installer#2]
I think the user should be required to accept the Microsoft EULA

I don't know whether this would make this legal, but I think just unpacking the .exe and install some parts of it without accepting the EULA I don't think it is

**Comment by ronaldtse** [comment]
@raffaem that does make sense, we may update this script to require acceptance of the EULA.

On the other hand, I suggest you utilize the [fontist gem](https://github.com/fontist/fontist) which already does that and supports many other fonts. The script here is more for historic purposes or limited environments that do not support Ruby.
