### ISSUE TITLE
Mint support

### ISSUE THREAD

**Issue by thilop** [fontist/vista-fonts-installer#4]
As Mint is essentially the same ad Ubuntu it should be supported. How should I add the support to test it?

**Comment by thilop** [comment]
cat /etc/os-release
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

**Comment by ronaldtse** [comment]
@hassanakbar would you have time to handle this? Thanks!

**Comment by HassanAkbar** [comment]
> @thilop thank you for the suggestion!
> 
> @HassanAkbar would you have time to handle this? Thanks!

@ronaldtse yes I will handle it.

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar !

**Comment by thilop** [comment]
I can confirm that it works. Thank you!

**Comment by ronaldtse** [comment]
Thanks @thilop and @HassanAkbar !
